In [56]:
import numpy as np
from sklearn.mixture import GaussianMixture
from collections import Counter, defaultdict
import pandas as pd

## Задача 1

### Выборки размера 10 и 5

In [80]:
n1 = 10 #мю=0, сигма=1
n2 = 5  #мю=1, сигма=1

x1 = np.random.normal(loc=0, scale=1, size=n1) #N(0, 1)
x2 = np.random.normal(loc=1, scale=1, size=n2) #N(1, 1)

x = np.concatenate([x1, x2])

np.random.shuffle(x)

print(x)

[ 0.52947896 -0.05693393 -1.08496999  1.54129889  2.27248032  1.68687883
 -1.52406648  0.97602747 -0.97238437  1.44494228  0.62829353  0.31243205
 -1.34822409 -0.17400109  0.02951448]


In [81]:
mu1, mu2 = np.random.choice(x.flatten(), 2, replace=False)
var1, var2 = 1, 1
pi1, pi2 = 0.5, 0.5

def normal_pdf(x, mean, var):
    return (1 / np.sqrt(2 * np.pi * var)) * np.exp(-0.5 * ((x - mean) ** 2) / var)

tol = 1e-6
max_iter = 100
log_likelihood_old = 0

for iteration in range(max_iter):
    r1 = pi1 * normal_pdf(x, mu1, var1)
    r2 = pi2 * normal_pdf(x, mu2, var2)

    sum_r = r1 + r2
    gamma1 = r1 / sum_r
    gamma2 = r2 / sum_r

    pi1 = np.mean(gamma1)
    pi2 = np.mean(gamma2)

    mu1 = np.sum(gamma1 * x.flatten()) / np.sum(gamma1)
    mu2 = np.sum(gamma2 * x.flatten()) / np.sum(gamma2)

    log_likelihood = np.sum(np.log(sum_r))

    if np.abs(log_likelihood - log_likelihood_old) < tol:
        break
    log_likelihood_old = log_likelihood

labels = (gamma2 > gamma1).astype(int)
count1 = np.sum(labels == 0)
count2 = np.sum(labels == 1)

print(f"Матожидание компоненты 1: {mu1}, количество чисел: {count1}")
print(f"Матожидание компоненты 2: {mu2}, количество чисел: {count2}")
print("\nВероятности принадлежности к компоненте 1:")
print(gamma1)
print("\nВероятности принадлежности к компоненте 2:")
print(gamma2)

Матожидание компоненты 1: -0.38344116158402375, количество чисел: 7
Матожидание компоненты 2: 0.8636451113311001, количество чисел: 8

Вероятности принадлежности к компоненте 1:
[0.37718988 0.55719883 0.81933194 0.1463779  0.06445712 0.12511661
 0.88689492 0.25762156 0.79761051 0.16203905 0.34870849 0.44254944
 0.8629632  0.59285767 0.53046089]

Вероятности принадлежности к компоненте 2:
[0.62281012 0.44280117 0.18066806 0.8536221  0.93554288 0.87488339
 0.11310508 0.74237844 0.20238949 0.83796095 0.65129151 0.55745056
 0.1370368  0.40714233 0.46953911]


### Выборки 100 и 50

In [82]:
n1 = 100 #мю=0, сигма=1
n2 = 50  #мю=1, сигма=1

x1 = np.random.normal(loc=0, scale=1, size=n1) #N(0, 1)
x2 = np.random.normal(loc=1, scale=1, size=n2) #N(1, 1)

x = np.concatenate([x1, x2])

np.random.shuffle(x)

print(x)

[ 7.99847348e-02  1.45981537e+00  1.18778665e+00  1.25401956e-01
  5.82320469e-01  8.97154492e-01 -1.40729034e+00  5.76647514e-01
 -2.09320177e-01  7.19828004e-01  9.42029798e-01  1.67348808e+00
  2.08913877e+00 -9.67968733e-01  9.59073626e-01 -8.43226571e-01
 -1.54471138e+00  3.26098089e-01 -3.52533297e-01  1.80575846e+00
  7.52753956e-01  6.21670928e-01  1.73729354e-01 -1.65570701e-01
 -1.16175624e+00 -3.13985036e-01 -2.02571647e-01  8.04404123e-01
 -7.09032945e-02  7.58873858e-02 -2.14844298e-01 -8.57000890e-01
 -3.97322062e-01  5.14423164e-01  1.05345395e-01  6.72975605e-01
  7.77814475e-01 -7.90002988e-01  9.04748031e-01  2.89851181e-01
 -9.03452535e-01  3.61087309e+00  8.86784469e-01  6.33151204e-01
 -3.11795839e-01  2.73557918e+00  7.71762654e-01  1.11775073e+00
 -2.55786465e-02  1.45913908e+00  1.61700112e+00  6.88407660e-01
 -3.01032695e-01  2.76318737e+00  1.47018939e+00  1.07971460e+00
  7.34227706e-01  5.09532296e-01 -7.86261519e-01 -1.36213792e+00
  1.02856691e-01 -1.59829

In [83]:
mu1, mu2 = np.random.choice(x.flatten(), 2, replace=False)
var1, var2 = 1, 1
pi1, pi2 = 0.5, 0.5

def normal_pdf(x, mean, var):
    return (1 / np.sqrt(2 * np.pi * var)) * np.exp(-0.5 * ((x - mean) ** 2) / var)

tol = 1e-6
max_iter = 100
log_likelihood_old = 0

for iteration in range(max_iter):
    r1 = pi1 * normal_pdf(x, mu1, var1)
    r2 = pi2 * normal_pdf(x, mu2, var2)

    sum_r = r1 + r2
    gamma1 = r1 / sum_r
    gamma2 = r2 / sum_r

    pi1 = np.mean(gamma1)
    pi2 = np.mean(gamma2)

    mu1 = np.sum(gamma1 * x.flatten()) / np.sum(gamma1)
    mu2 = np.sum(gamma2 * x.flatten()) / np.sum(gamma2)

    log_likelihood = np.sum(np.log(sum_r))

    if np.abs(log_likelihood - log_likelihood_old) < tol:
        break
    log_likelihood_old = log_likelihood

labels = (gamma2 > gamma1).astype(int)
count1 = np.sum(labels == 0)
count2 = np.sum(labels == 1)

print(f"Матожидание компоненты 1: {mu1}, количество чисел: {count1}")
print(f"Матожидание компоненты 2: {mu2}, количество чисел: {count2}")
print("\nВероятности принадлежности к компоненте 1:")
print(gamma1)
print("\nВероятности принадлежности к компоненте 2:")
print(gamma2)

Матожидание компоненты 1: 0.2446492821182246, количество чисел: 146
Матожидание компоненты 2: 0.6810681874080182, количество чисел: 4

Вероятности принадлежности к компоненте 1:
[0.73348323 0.60115808 0.62924744 0.72959134 0.68851342 0.65831719
 0.84041573 0.68904404 0.75742301 0.6755024  0.6538992  0.57860732
 0.53387156 0.81300132 0.65221419 0.80458501 0.84829451 0.71197152
 0.76871904 0.56447505 0.67234529 0.6848192  0.72541102 0.75389839
 0.82551783 0.76571508 0.75688157 0.6673613  0.74615433 0.73383258
 0.7578656  0.80552827 0.77217535 0.69483141 0.73131443 0.67996743
 0.66993184 0.80090778 0.6575715  0.71520396 0.80868376 0.37091373
 0.65933426 0.68373698 0.76554367 0.46347182 0.67051548 0.63634821
 0.74239022 0.60122883 0.58460497 0.67850035 0.76469968 0.46047761
 0.60007226 0.64018007 0.67412362 0.69528373 0.80064733 0.83775563
 0.73152775 0.85127871 0.58526952 0.72354365 0.6780598  0.48881804
 0.68238686 0.59772878 0.62518222 0.78581401 0.60818815 0.5448318
 0.76727352 0.83400

### Выборки 1000 и 500

In [86]:
n1 = 1000 #мю=0, сигма=1
n2 = 500  #мю=1, сигма=1

x1 = np.random.normal(loc=0, scale=1, size=n1) #N(0, 1)
x2 = np.random.normal(loc=1, scale=1, size=n2) #N(1, 1)

x = np.concatenate([x1, x2])

np.random.shuffle(x)

print(x)

[-1.0652184  -0.33712346 -0.68125287 ...  0.1721963  -1.8675845
 -1.67820097]


In [87]:
mu1, mu2 = np.random.choice(x.flatten(), 2, replace=False)
var1, var2 = 1, 1
pi1, pi2 = 0.5, 0.5

def normal_pdf(x, mean, var):
    return (1 / np.sqrt(2 * np.pi * var)) * np.exp(-0.5 * ((x - mean) ** 2) / var)

tol = 1e-6
max_iter = 100
log_likelihood_old = 0

for iteration in range(max_iter):
    r1 = pi1 * normal_pdf(x, mu1, var1)
    r2 = pi2 * normal_pdf(x, mu2, var2)

    sum_r = r1 + r2
    gamma1 = r1 / sum_r
    gamma2 = r2 / sum_r

    pi1 = np.mean(gamma1)
    pi2 = np.mean(gamma2)

    mu1 = np.sum(gamma1 * x.flatten()) / np.sum(gamma1)
    mu2 = np.sum(gamma2 * x.flatten()) / np.sum(gamma2)

    log_likelihood = np.sum(np.log(sum_r))

    if np.abs(log_likelihood - log_likelihood_old) < tol:
        break
    log_likelihood_old = log_likelihood

labels = (gamma2 > gamma1).astype(int)
count1 = np.sum(labels == 0)
count2 = np.sum(labels == 1)

print(f"Матожидание компоненты 1: {mu1}, количество чисел: {count1}")
print(f"Матожидание компоненты 2: {mu2}, количество чисел: {count2}")
print("\nВероятности принадлежности к компоненте 1:")
print(gamma1)
print("\nВероятности принадлежности к компоненте 2:")
print(gamma2)

Матожидание компоненты 1: 0.8096362348108159, количество чисел: 585
Матожидание компоненты 2: -0.06754543497813564, количество чисел: 915

Вероятности принадлежности к компоненте 1:
[0.18953165 0.3069429  0.24670131 ... 0.40908945 0.10369709 0.12018306]

Вероятности принадлежности к компоненте 2:
[0.81046835 0.6930571  0.75329869 ... 0.59091055 0.89630291 0.87981694]


## Задача 2

### Генерация последовательностей

In [88]:
states = ['a', 'b']
initial_probs = np.array([0.5, 0.5])
transition_matrix = np.array([
    [0.7, 0.3],
    [0.6, 0.4]
])

num_sequences = 1000
sequence_length = 3000

initial_states = np.random.choice(states, size=num_sequences, p=initial_probs)
sequences = np.empty((num_sequences, sequence_length), dtype=str)
sequences[:, 0] = initial_states

for i in range(1, sequence_length):
    prev_indices = (sequences[:, i-1] == 'a').astype(int)
    probs = transition_matrix[prev_indices]
    sequences[:, i] = np.where(
        np.random.rand(num_sequences) < probs[:, 0], 'a', 'b'
    )

unique, counts = np.unique(sequences[:, 0], return_counts=True)
estimated_initial_probs = counts / num_sequences

transition_counts = np.zeros((2, 2))
state_index = {'a': 0, 'b': 1}
prev_states = sequences[:, :-1].ravel()
next_states = sequences[:, 1:].ravel()
for p, n in zip(prev_states, next_states):
    transition_counts[state_index[p], state_index[n]] += 1

estimated_transition_matrix = transition_counts / transition_counts.sum(axis=1, keepdims=True)

print("Исходные вероятности начальных состояний:", initial_probs)
print("Оцененные вероятности начальных состояний:", estimated_initial_probs)

print("Исходная матрица переходов:")
print(transition_matrix)

print("Оцененная матрица переходов:")
print(estimated_transition_matrix)

Исходные вероятности начальных состояний: [0.5 0.5]
Оцененные вероятности начальных состояний: [0.509 0.491]
Исходная матрица переходов:
[[0.7 0.3]
 [0.6 0.4]]
Оцененная матрица переходов:
[[0.59986737 0.40013263]
 [0.69940952 0.30059048]]


### Сравнение моделей

In [89]:
flattened_seq = sequences.ravel()
n = len(flattened_seq)

#бернулли
counts = Counter(flattened_seq)
total = sum(counts.values())
bernoulli_probs = {k: v / total for k, v in counts.items()}

log_likelihood_bernoulli = sum([v * np.log(bernoulli_probs[k]) for k, v in counts.items()])
k_bernoulli = len(bernoulli_probs)
AIC_bernoulli = 2 * k_bernoulli - 2 * log_likelihood_bernoulli
BIC_bernoulli = k_bernoulli * np.log(n) - 2 * log_likelihood_bernoulli

#марковская 1
transition_counts_1 = np.zeros((2, 2))
state_index = {'a': 0, 'b': 1}

for i in range(1, len(flattened_seq)):
    prev_idx = state_index[flattened_seq[i-1]]
    curr_idx = state_index[flattened_seq[i]]
    transition_counts_1[prev_idx, curr_idx] += 1

transition_probs_1 = transition_counts_1 / transition_counts_1.sum(axis=1, keepdims=True)

log_likelihood_1 = np.sum(transition_counts_1 * np.log(transition_probs_1, where=(transition_probs_1>0)))
k_1 = 2 * (2 - 1)
AIC_1 = 2 * k_1 - 2 * log_likelihood_1
BIC_1 = k_1 * np.log(n) - 2 * log_likelihood_1

#марковская 2
transition_counts_2 = defaultdict(lambda: Counter())

for i in range(2, len(flattened_seq)):
    prev_state = (flattened_seq[i-2], flattened_seq[i-1])
    curr_state = flattened_seq[i]
    transition_counts_2[prev_state][curr_state] += 1

transition_probs_2 = {
    k: {kk: vv / sum(v.values()) for kk, vv in v.items()}
    for k, v in transition_counts_2.items()
}

log_likelihood_2 = sum([
    count * np.log(transition_probs_2[k][kk])
    for k, v in transition_counts_2.items()
    for kk, count in v.items()
    if transition_probs_2[k][kk] > 0
])
k_2 = len(transition_probs_2) * (2 - 1)
AIC_2 = 2 * k_2 - 2 * log_likelihood_2
BIC_2 = k_2 * np.log(n) - 2 * log_likelihood_2

#марковская 3
transition_counts_3 = defaultdict(lambda: Counter())

for i in range(3, len(flattened_seq)):
    prev_state = (flattened_seq[i-3], flattened_seq[i-2], flattened_seq[i-1])
    curr_state = flattened_seq[i]
    transition_counts_3[prev_state][curr_state] += 1

transition_probs_3 = {
    k: {kk: vv / sum(v.values()) for kk, vv in v.items()}
    for k, v in transition_counts_3.items()
}

log_likelihood_3 = sum([
    count * np.log(transition_probs_3[k][kk])
    for k, v in transition_counts_3.items()
    for kk, count in v.items()
    if transition_probs_3[k][kk] > 0
])
k_3 = len(transition_probs_3) * (2 - 1)
AIC_3 = 2 * k_3 - 2 * log_likelihood_3
BIC_3 = k_3 * np.log(n) - 2 * log_likelihood_3


results = pd.DataFrame({
    'Model': ['Bernoulli', 'Markov 1', 'Markov 2', 'Markov 3'],
    'AIC': [AIC_bernoulli, AIC_1, AIC_2, AIC_3],
    'BIC': [BIC_bernoulli, BIC_1, BIC_2, BIC_3]
})

print(results)

       Model           AIC           BIC
0  Bernoulli  3.933935e+06  3.933961e+06
1   Markov 1  3.903825e+06  3.903850e+06
2   Markov 2  3.903824e+06  3.903876e+06
3   Markov 3  3.903823e+06  3.903927e+06


Лучше всего описывает данные Марковская модель 3-го порядка, тк имеет наименьшие критерии AIC и BIC.

### Bacillus subtillis

In [ ]:
#from google.colab import files
#uploaded = files.upload()

In [90]:
def read_fasta(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()
    return ''.join([line.strip() for line in lines if not line.startswith('>')])

def split_sequence(sequence, chunk_size=1000):
    return [sequence[i:i + chunk_size] for i in range(0, len(sequence), chunk_size) if len(sequence[i:i + chunk_size]) == chunk_size]

#бернулли
def bernoulli_model(sequences):
    counts = Counter(''.join(sequences))
    total = sum(counts.values())
    probs = {k: v / total for k, v in counts.items()}
    log_likelihood = sum([v * np.log(probs[k]) for k, v in counts.items()])
    k = len(probs)
    return log_likelihood, k

#марковская
def markov_model(sequences, order):
    transition_counts = defaultdict(lambda: Counter())

    for seq in sequences:
        for i in range(order, len(seq)):
            prev_state = tuple(seq[i - order:i])
            curr_state = seq[i]
            transition_counts[prev_state][curr_state] += 1

    transition_probs = {
        k: {kk: vv / sum(v.values()) for kk, vv in v.items()}
        for k, v in transition_counts.items()
    }

    log_likelihood = sum([
        count * np.log(transition_probs[k][kk])
        for k, v in transition_counts.items()
        for kk, count in v.items()
        if transition_probs[k][kk] > 0
    ])

    k = len(transition_probs) * (len(set(''.join(sequences))) - 1)
    return log_likelihood, k

def calculate_aic_bic(log_likelihood, k, n):
    AIC = 2 * k - 2 * log_likelihood
    BIC = k * np.log(n) - 2 * log_likelihood
    return AIC, BIC

def process_fasta(filename):
    sequence = read_fasta(filename)
    sequences = split_sequence(sequence, 1000)
    n = sum([len(seq) for seq in sequences])

    results = []

    log_likelihood, k = bernoulli_model(sequences)
    AIC, BIC = calculate_aic_bic(log_likelihood, k, n)
    results.append(['Bernoulli', AIC, BIC])

    for order in range(1, 6):
        log_likelihood, k = markov_model(sequences, order)
        AIC, BIC = calculate_aic_bic(log_likelihood, k, n)
        results.append([f'Markov {order}', AIC, BIC])

    return pd.DataFrame(results, columns=['Model', 'AIC', 'BIC'])

results = process_fasta('sequence.fasta')
print(results)

       Model           AIC           BIC
0  Bernoulli  1.161535e+07  1.161540e+07
1   Markov 1  1.146184e+07  1.146200e+07
2   Markov 2  1.136611e+07  1.136674e+07
3   Markov 3  1.131769e+07  1.132023e+07
4   Markov 4  1.129097e+07  1.130115e+07
5   Markov 5  1.126834e+07  1.130906e+07


Лучше всего подошла марковская модель 5 порядка, так как имеет наименьшие значения AIC и BIC